/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
import { Product } from "./components/app-product-listing/product.model";
export namespace Components {
    interface AppCart {
    }
    interface AppProduct {
        "match": MatchResults;
    }
    interface AppProductListing {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppCartElement extends Components.AppCart, HTMLStencilElement {
    }
    var HTMLAppCartElement: {
        prototype: HTMLAppCartElement;
        new (): HTMLAppCartElement;
    };
    interface HTMLAppProductElement extends Components.AppProduct, HTMLStencilElement {
    }
    var HTMLAppProductElement: {
        prototype: HTMLAppProductElement;
        new (): HTMLAppProductElement;
    };
    interface HTMLAppProductListingElement extends Components.AppProductListing, HTMLStencilElement {
    }
    var HTMLAppProductListingElement: {
        prototype: HTMLAppProductListingElement;
        new (): HTMLAppProductListingElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-cart": HTMLAppCartElement;
        "app-product": HTMLAppProductElement;
        "app-product-listing": HTMLAppProductListingElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppCart {
    }
    interface AppProduct {
        "match"?: MatchResults;
        "onProductAddedToCart"?: (event: CustomEvent<Product>) => void;
    }
    interface AppProductListing {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-cart": AppCart;
        "app-product": AppProduct;
        "app-product-listing": AppProductListing;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-cart": LocalJSX.AppCart & JSXBase.HTMLAttributes<HTMLAppCartElement>;
            "app-product": LocalJSX.AppProduct & JSXBase.HTMLAttributes<HTMLAppProductElement>;
            "app-product-listing": LocalJSX.AppProductListing & JSXBase.HTMLAttributes<HTMLAppProductListingElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
